import type { ToolchainProviderConfig, ToolchainTaskConfig } from "./types";

export const TOOLCHAIN_TASKS: Record<string, ToolchainTaskConfig> = {
  source_search: {
    task: "source_search",
    defaultProvider: "tavily",
    fallbackProvider: "manual",
    costLevel: "low",
    requiresEvidence: true,
    notes: "公开网页来源获取；没有链接的结果只能作为待验证信号。",
  },
  source_verify: {
    task: "source_verify",
    defaultProvider: "tavily",
    fallbackProvider: "openai_web_search",
    costLevel: "medium",
    requiresEvidence: true,
    notes: "验证来源链接和摘要，不得虚构链接。",
  },
  topic_rank: {
    task: "topic_rank",
    defaultProvider: "deepseek",
    fallbackProvider: "openai",
    costLevel: "low",
    requiresEvidence: false,
    notes: "基于来源、定位和适配度做选题排序。",
  },
  angle_generate: {
    task: "angle_generate",
    defaultProvider: "deepseek",
    fallbackProvider: "openai",
    costLevel: "low",
    requiresEvidence: false,
    notes: "生成细分切入角度。",
  },
  outline_generate: {
    task: "outline_generate",
    defaultProvider: "deepseek",
    fallbackProvider: "openai",
    costLevel: "low",
    requiresEvidence: false,
    notes: "生成公众号文章大纲。",
  },
  article_write: {
    task: "article_write",
    defaultProvider: "deepseek",
    fallbackProvider: "openai",
    costLevel: "medium",
    requiresEvidence: true,
    notes: "写作必须基于已有来源证据，来源不足时提示待验证。",
  },
  style_rewrite: {
    task: "style_rewrite",
    defaultProvider: "deepseek",
    fallbackProvider: "openai",
    costLevel: "medium",
    requiresEvidence: false,
    notes: "七七语气和表达优化。",
  },
  layout_render: {
    task: "layout_render",
    defaultProvider: "wechat_html_template",
    costLevel: "free",
    requiresEvidence: false,
    notes: "本地公众号 HTML 模板渲染。",
  },
  cover_generate: {
    task: "cover_generate",
    defaultProvider: "manual_upload",
    fallbackProvider: "ai_cover",
    costLevel: "free",
    requiresEvidence: false,
    notes: "当前为手动上传封面，AI 封面仅预留。",
  },
  draft_publish: {
    task: "draft_publish",
    defaultProvider: "wechat_draft_api",
    costLevel: "free",
    requiresEvidence: false,
    notes: "只写入公众号草稿箱，不自动发布。",
  },
  feishu_push: {
    task: "feishu_push",
    defaultProvider: "feishu_webhook",
    costLevel: "free",
    requiresEvidence: false,
    notes: "飞书 webhook 推送；交互卡片回调后置。",
  },
};

export const RESERVED_DATA_PROVIDERS: ToolchainProviderConfig[] = [
  {
    provider: "feishu_inspiration",
    status: "not_connected",
    priority: 1,
    notes: "适合优先接入飞书灵感或人工观察源，需结构化入池。",
  },
  {
    provider: "manual_source",
    status: "connected",
    priority: 1,
    notes: "当前手动来源池，需强化来源证据结构。",
  },
  {
    provider: "newrank",
    status: "not_connected",
    priority: 2,
    notes: "新榜数据源预留；接入前需确认账号、授权和 API 条款。",
  },
  {
    provider: "douyin_index",
    status: "not_connected",
    priority: 3,
    notes: "抖音指数预留；只走官方或授权数据。",
  },
  {
    provider: "oceanengine_trend",
    status: "not_connected",
    priority: 3,
    notes: "巨量/巨量算数趋势预留；只走官方或授权数据。",
  },
  {
    provider: "xiaohongshu_observation",
    status: "not_connected",
    priority: 4,
    notes: "小红书观察源预留；不做违规爬取。",
  },
  {
    provider: "douyin_official",
    status: "not_connected",
    priority: 5,
    notes: "抖音官方数据预留；需账号和权限。",
  },
  {
    provider: "video_account_signal",
    status: "not_connected",
    priority: 5,
    notes: "视频号信号预留；需合规来源。",
  },
];
